### ISSUE TITLE
Add Sine/Cosine Function

### ISSUE THREAD

**Issue by Sir-Bip-Bop** [QuanticPony/itfit#19]
Sine and Cosine function must support amplitude, phase and constant offset.

**Comment by Sir-Bip-Bop** [comment]
The way it's set up right now it  only uses sin functions, is it worth it to change the function to cosine depending on the point positions?

**Comment by QuanticPony** [comment]
I don't think the function should change. I would add the cosine and focus on thinking a better way of choosing functions
